version: '3'
services:
  db:
    image: 192.168.40.9:5000/mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: achatdb

  spring-boot-app:
    depends_on:
      - db
    image: 192.168.40.9:5000/spring:new
    container_name: spring
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/achatdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
